Update to printf-compat 0.2.1
This fixes the build error:
```
error[E0277]: the trait bound `i8: VaArgSafe` is not satisfied
   --> /home/mateusz/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/printf-compat-0.1.1/src/parser.rs:80:50
    |
 80 |             Length::Char => SignedInt::Char(args.arg()),
    |                                                  ^^^ the trait `VaArgSafe` is not implemented for `i8`
    |
    = help: the following other types implement trait `VaArgSafe`:
              f64
              i32
              i64
              isize
              u32
              u64
              usize
```